[build]
  command = "npm run build"
  publish = "dist"
  base = "Campus_Exchange"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/listings/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/item/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/post-item"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/index.html"
  status = 200